finchcollector/urls.py
from django.contrib import admin
# Add the include function to the import
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    # include the built-in auth urls for the built-in views
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('about/', views.about, name='about'),
  path('cars/', views.car_index, name='car-index'),
  path('cars/<int:car_id>/', views.car_detail, name='car-detail'),
  path('cars/create/', views.CarCreate.as_view(), name='car-create'),
  path('cars/<int:pk>/update/', views.CarUpdate.as_view(), name='car-update'),
  path('cars/<int:pk>/delete/', views.CarDelete.as_view(), name='car-delete'),
  path('cars/<int:car_id>/add-service/', views.add_service, name='add-service'),
  path('cars/<int:car_id>/assoc-mod/<int:mod_id>/', views.assoc_mod, name='assoc-mod'),
  path('mods/create/', views.ModCreate.as_view(), name='mod-create'),
  path('mods/<int:pk>/', views.ModDetail.as_view(), name='mod-detail'),
  path('mods/', views.ModList.as_view(), name='mod-index'),
  path('mods/<int:pk>/update/', views.ModUpdate.as_view(), name='mod-update'),
  path('toys/<int:pk>/delete/', views.ModDelete.as_view(), name='mod-delete'),
  path('', views.Home.as_view(), name='home'),
  path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Mod(models.Model):
  name = models.CharField(max_length=50)
  description = models.CharField(max_length=20)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('mod-detail', kwargs={'pk': self.id})
class Car(models.Model):
  model = models.CharField(max_length=100)
  year = models.IntegerField()
  description = models.TextField(max_length=250)
  mods = models.ManyToManyField(Mod)
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
    return self.model
  
  def get_absolute_url(self):
    return reverse('car-detail', kwargs={'car_id': self.id})
  
class Service(models.Model):
  date = models.DateField('Service date')
  repair = models.CharField(max_length=250)

  car = models.ForeignKey(Car, on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.repair} on {self.date}"
  
  class Meta:
    ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Service

class ServiceForm(ModelForm):
  class Meta:
    model = Service
    fields = ['date', 'repair']

main_app/views.py
from django.shortcuts import render, redirect
from .models import Car, Mod
from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .forms import ServiceForm
from django.contrib.auth.views import LoginView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Define the home view
def about(request):
  return render(request, 'about.html')

@login_required
def car_index(request):
  cars = Car.objects.filter(user=request.user)
  return render(request, 'cars/index.html', { 'cars': cars })

class Home(LoginView):
  template_name = 'home.html'

@login_required
def car_detail(request, car_id):
  car = Car.objects.get(id=car_id)
  mods_car_doesnt_have = Mod.objects.exclude(id__in = car.mods.all().values_list('id'))
  service_form = ServiceForm()
  return render(request, 'cars/detail.html', {
    'car': car, 'service_form': service_form, 'mods': mods_car_doesnt_have
  })

@login_required
def add_service(request, car_id):
  form = ServiceForm(request.POST)
  if form.is_valid():
    new_service = form.save(commit=False)
    new_service.car_id = car_id
    new_service.save()
  return redirect('car-detail', car_id=car_id)

class CarCreate(CreateView):
  model = Car
  fields = 'model', 'year', 'description'
  success_url = '/cars'

  def form_valid(self, form):
    # Assign the logged in user (self.request.user)
    form.instance.user = self.request.user  # form.instance is the cat
    # Let the CreateView do its job as usual
    return super().form_valid(form)

class CarUpdate(LoginRequiredMixin, UpdateView):
  model = Car
  fields = ['year', 'description']

class CarDelete(LoginRequiredMixin, DeleteView):
  model = Car
  success_url = '/cars/'

class ModCreate(LoginRequiredMixin, CreateView):
  model = Mod
  fields = '__all__'

class ModList(LoginRequiredMixin, ListView):
  model = Mod

class ModDetail(LoginRequiredMixin, DetailView):
  model = Mod

class ModUpdate(LoginRequiredMixin, UpdateView):
  model = Mod
  fields = ['name', 'color']

class ModDelete(LoginRequiredMixin, DeleteView):
  model = Mod
  success_url = '/mods/'

@login_required
def assoc_mod(request, car_id, mod_id):
  # Note that you can pass a toy's id instead of the whole object
  Car.objects.get(id=car_id).mods.add(mod_id)
  return redirect('car-detail', car_id=car_id)

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in
      login(request, user)
      return redirect('car-index')
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'signup.html', context)
  # Same as: return render(request, 'signup.html', {'form': form, 'error_message': error_message})

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}

<h1>About the Car Collector</h1>
<hr />
<p class="page-content">
  An easy way to keep track of cars you own or cars on your wishlist!
</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link
    rel="shortcut icon"
    type="image/png"
    href=""
  >
  <title>Car Collector</title>

  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">

  {% block head %}
  {% endblock %}
</head>
<body>
  <header>
    <div class="header-logo-container">
      <a href="{% url 'home' %}">
        <img 
          src="{% static 'images/car.svg' %}"
          alt="The Cat Collector Logo"
          width='30'
          height='30'
          class="logo-image"
        >
        Car Collector
      </a>
    </div>
    <nav>
      <ul>
        {% if user.is_authenticated %}
          <li><a href="{% url 'car-index' %}">All Cars</a></li>
          <li><a href="{% url 'car-create' %}">Add a Car</a></li>
          <li><a href="{% url 'mod-create' %}">Add a Mod</a></li>
          <li><a href="{% url 'mod-index' %}">All Mods</a></li>
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'logout' %}">Log out</a></li>
        {% else %}
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'home' %}">Login</a></li>
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
        {% endif %}
      </ul>
    </nav>
  </header>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

main_app/templates/cars/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  href="https://cdn.jsdelivr.net/npm/mc-datepicker/dist/mc-calendar.min.css" 
  rel="stylesheet" 
/>
<link rel="stylesheet" href="{% static 'css/mcdp.css' %}">
<script 
  src="https://cdn.jsdelivr.net/npm/mc-datepicker/dist/mc-calendar.min.js"
>
</script>
<link 
  rel="stylesheet" 
  type="text/css" 
  href="{% static 'css/cars/car-detail.css' %}"
/>
<script defer src="{% static 'js/car-detail.js' %}"></script>
{% endblock %}

{% block content %}

<section class="cat-container">
  <div class="cat-img">
    <img class="card-image" 
      src="{% static 'images/car.svg' %}" 
      alt="A car image"
    >
  </div>
  <div class="cat-details">
    <h2 class="card-title">{{ car.model }}</h2>
      <p>A {{ car.year }} {{ car.model }}</p>
    <p><small>{{ car.description }}</small></p>
    <div class="cat-actions">
      <a href="{% url 'car-update' car.id %}" class="btn warn">Edit</a>
      <a href="{% url 'car-delete' car.id %}" class="btn danger">Delete</a>
    </div>
  </div>
</section>
<div class="feedings-toy-container">
  <section class="feedings">
    <div class="subsection-title">
      <h2>Services</h2>
    </div>
    <h3>Add a Service</h3>
    <form
      action="{% url 'add-service' car.id %}" 
      method="post" 
      class="subsection-content"
			autocomplete="off"
    >
      {% csrf_token %}
      {{ service_form.as_p }}
      <button type="submit" class="btn submit">Add Service</button>
    </form>
    <h3>Past Services</h3>
    {% if car.service_set.all.count %}
      <table>
        <thead>
          <tr><th>Date</th><th>Repair</th></tr>
        </thead>
        <tbody>
          {% for service in car.service_set.all %}
            <tr>
              <td>{{service.date}}</td>
              <td>{{service.repair}}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
			<div class="subsection-content">
        <p>{{car.name}} has never been serviced 😔</p>
      </div>
    {% endif %}
  </section>
  <section class="toys">
    <div class="subsection-title">
      <h2>Mods</h2>
    </div>
    <h3>{{ car.model }}'s Mods</h3>
    <div class="subsection-content">
      {% if car.mods.count %}
        {% for mod in cat.mods.all %}
          <div class="toy-container">
            <div 
              class="color-block"
            ></div>
            <a href="{% url 'mod-detail' mod.id %}">
              <p>A {{ mod.name }}</p>
            </a>
          </div>
        {% endfor %}
      {% else %}
        <p class="no-toys">{{car.model}} doesn't have any mods 😞</p>
      {% endif %}
    </div>
    <h3>Available Mods</h3>
    <div class="subsection-content">
      {% comment %} We'll display available toys here {% endcomment %}
      {% if mods.count %}
        {% for mod in mods.all %}
          <div class="toy-container">
            <div 
              class="color-block"
            ></div>
            <a href="{% url 'mod-detail' mod.id %}">
              <p>A {{ mod.name }}</p>
            </a>
            <form action="{% url 'assoc-mod' car.id mod.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn submit">Add mod</button>
            </form>
          </div>
        {% endfor %}
      {% else %}
        <p class="all-toys">
          {{car.model}} already has all the available mods 🥳
        </p>
      {% endif %}
    </div>
  </section>
</div>


{% endblock %}

main_app/templates/cars/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/cars/car-index.css' %}"
/>
{% endblock %}

{% block content %}

<section class="page-header">
  <h1>Car List</h1>
</section>

<section class="card-container">
  {% for car in cars %}
    <div class="card">
      <a href="{% url 'car-detail' car.id %}">
        <div class="card-content">
          <div class="card-img-container">
            <img class="card-image" 
              src="{% static 'images/car.svg' %}" 
              alt="A car image"
            >
          </div>
          <h2 class="card-title">{{ car.model }}</h2>
            <p>A vehicle made in {{ car.year }}</p>
        </div>
      </a>
    </div>
  {% endfor %}
</section>

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}"/>
{% endblock %}

{% block content %}

<section class="logo-container">
  <div class="cat-container">
    <img src="{% static 'images/car.svg' %}" alt="The Car Collector Car" width="100" height="100"/>
  </div>
</section>

{% if not user.is_authenticated %}
  <section>
    <form action="{% url 'home' %}" method="post" class="login">
      <h1>Login</h1>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="hidden" name="next" value="{{ next }}">
      <button type="submit" class="btn submit">Login</button>
    </form>
  </section>
{% endif %}

{% endblock %}

main_app/templates/main_app/car_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="page-header">
  <h1>Remove car from garage?</h1>
</div>
<h2>Are you remove {{car.model}} from your garage?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a 
    href="{% url 'car-detail' car.id %}" 
    class="btn secondary"
  >
    Cancel
  </a>
  <button type="submit" class="btn danger">Remove {{car.model}}!</button>
</form>

{% endblock %}

main_app/templates/main_app/car_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}

<div class="page-header">
  {% if car %}
    <h1>Edit {{ car.model }}</h1>
  {% else %}
    <h1>Add a Car</h1>
  {% endif %}
</div>
{% comment %} 
  Leaving the action empty makes the form post to the same url used to display it
{% endcomment %}
<form action="" method="post" class="form-container">
  {% comment %} 
    Django requires the following for security purposes
  {% endcomment %}
  {% csrf_token %}
  <table>
    {% comment %}
      Render the inputs inside of <tr>s & <td>s
    {% endcomment %}
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

main_app/templates/main_app/mod_detail.html
{% extends 'base.html' %} 
{% load static %} 

{% block head %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/toys/toy-detail.css' %}"
/>
{% endblock %}

{% block content %}
  
<div class="card">
  <div class="card-bg"></div>
  <div class="card-content">
    <h2>{{ mod.name }}</h2>
    <p>{{ mod.description }}</p>
  </div>
</div>
<a href="{% url 'mod-update' mod.id %}" class="btn warn">Edit</a>
<a href="{% url 'mod-delete' mod.id %}" class="btn danger">Delete</a>

{% endblock %}

main_app/templates/main_app/mod_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}
<div class="page-header">
  {% if object %}
    <h1>Edit {{object.name}}</h1>
  {% else %}
    <h1>Add a Mod</h1>
  {% endif %}
</div>
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

main_app/templates/main_app/mod_list.html
{% extends 'base.html' %} 
{% load static %} 

{% block head %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/mods/mod-index.css' %}"
/>
{% endblock %}

{% block content %}

<section class="page-header">
  <h1>All Car Mods</h1>
</section>

<section class="card-container">
  {% for mod in mod_list %}
  <div class="card">
    <div class="card-bg"></div>
    <a href="{% url 'mod-detail' mod.id %}">
      <div class="card-content">
        <h2>{{ mod.name }}</h2>
        <p>{{ mod.description }}</p>
      </div>
    </a>
  </div>
  {% endfor %}
</section>

{% endblock %}

main_app/templates/main_app/toy_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="page-header">
  <h1>Delete Mod?</h1>
</div>
<h2>Are you sure you want to delete {{ object.name }}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a 
    href="{% url 'mod-detail' mod.id %}" 
    class="btn secondary"
  >
    Cancel
  </a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}

<div class="page-header">
  <h1>Sign Up</h1>
  <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer"/>
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}